import { useCallback, useEffect, useState } from 'react';
import { listGroupMessages, sendGroupMessage } from '@/services/groups.api.service';
import { useCommunityData } from './use-community-data';
import { Breadcrumbs } from '@/components/common/breadcrumbs';
import { Button } from '@/components/ui/button';
import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/card';
import type { StudentGroup } from '@/types/community';
export function GroupRoom({ group, onBack }: { group: StudentGroup; onBack: () => void }) {
  const load = useCallback(() => listGroupMessages(group._id), [group._id]);
  const { data, error, refresh } = useCommunityData(load);
  const [text, setText] = useState(''); const [pending, setPending] = useState(false); const [actionError, setActionError] = useState('');
  useEffect(() => { const timer = setInterval(refresh, 5000); return () => clearInterval(timer); }, [refresh]);
  return <div className="space-y-4"><Breadcrumbs items={[{ label: group.kind === 'practice' ? 'Self-Assessment' : 'Groups', onClick: onBack }, { label: group.name }]} /><Card><CardHeader><CardTitle>{group.name}</CardTitle><p className="text-sm text-muted-foreground whitespace-pre-wrap">{group.description}</p></CardHeader><CardContent><details><summary className="cursor-pointer font-medium">Participants ({group.participants.filter(p => p.status === 'accepted').length}) · Coordinators ({group.coordinators?.length || 0})</summary><div className="mt-3 grid gap-2 sm:grid-cols-3">{group.coordinators?.map(p => <div key={p._id} className="rounded-lg border p-3">{p.name}<p className="text-xs text-muted-foreground">Coordinator</p></div>)}{group.participants.filter(p => p.status === 'accepted').map((p, i) => <div key={p.student?._id || i} className="rounded-lg border p-3">{p.student?.name || 'Former student'}</div>)}</div></details></CardContent></Card><Card><CardHeader><CardTitle>Conversation</CardTitle></CardHeader><CardContent className="space-y-4">{error && <p role="alert">{error} <button onClick={refresh}>Retry</button></p>}<div role="log" aria-label="Group messages" className="max-h-[480px] space-y-3 overflow-y-auto">{data?.messages.map(m => <div key={m._id} className="rounded-lg bg-muted p-3"><div className="flex justify-between gap-2 text-xs text-muted-foreground"><span>{m.sender?.name || 'Former member'}</span><time>{new Date(m.createdAt).toLocaleString()}</time></div><p className="mt-1 whitespace-pre-wrap break-words">{m.text}</p></div>)}{data && !data.messages.length && <p className="text-sm text-muted-foreground">Start a conversation. Share a question, solution, or practice prompt.</p>}</div><form className="space-y-2" onSubmit={async event => { event.preventDefault(); if (!text.trim()) return; setPending(true); setActionError(''); try { await sendGroupMessage(group._id, text); setText(''); refresh(); } catch (e) { setActionError(e instanceof Error ? e.message : 'Message could not be sent'); } finally { setPending(false); } }}><textarea aria-label="Message" required maxLength={5000} className="min-h-24 w-full rounded-lg border p-3" value={text} disabled={pending} onChange={e => setText(e.target.value)} /><Button disabled={pending || !text.trim()}>{pending ? 'Sending…' : 'Send message'}</Button>{actionError && <p role="alert" className="text-destructive">{actionError}</p>}</form></CardContent></Card></div>;
}
