import { apiFetch } from '@/services/api-client';
import type { StudentGroup, GroupInvitation } from '@/types/community';
export const listGroups = () => apiFetch<{ groups: StudentGroup[] }>('/api/groups');
export const listGroupInvitations = () => apiFetch<{ invitations: GroupInvitation[] }>('/api/groups/invitations');
export const createGroup = (payload: { name: string; description: string; students: string[]; mode?: string }) => apiFetch<{ message: string }>('/api/groups', { method: 'POST', body: JSON.stringify(payload) });
export const inviteToGroup = (id: string, students: string[]) => apiFetch<{ message: string }>(`/api/groups/${id}/invitations`, { method: 'POST', body: JSON.stringify({ students }) });
export const respondToGroupInvitation = (id: string, status: 'accepted' | 'declined') => apiFetch<{ message: string }>(`/api/groups/${id}/invitations/me`, { method: 'PATCH', body: JSON.stringify({ status }) });
export const listPracticePeers = () => apiFetch<{ peers: import('@/types/community').Peer[] }>('/api/groups/peers');
export const listFaculty = () => apiFetch<{ faculty: import('@/types/api').ApiUser[] }>('/api/groups/coordinators');
export const listGroupMessages = (id: string) => apiFetch<{ messages: { _id: string; text: string; sender: import('@/types/community').Peer | null; createdAt: string }[] }>(`/api/groups/${id}/messages`);
export const sendGroupMessage = (id: string, text: string) => apiFetch(`/api/groups/${id}/messages`, { method: 'POST', body: JSON.stringify({ text }) });
export const assignGroupCoordinators = (id: string, coordinators: string[]) => apiFetch(`/api/groups/${id}/coordinators`, { method: 'PATCH', body: JSON.stringify({ coordinators }) });
