import { useCallback, useState } from 'react';
import { getCohortReadiness, getReadiness, listReadinessPolicies, recordAcademics, recordShortlistDecision } from '@/services/readiness.api.service';
import { useCommunityData } from '@/sections/community/use-community-data';
import { PageSkeleton, LoadError } from '@/components/common/loading-state';
import { SectionIntro } from '@/components/common/section-intro';
import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import type { ReadinessQuery, ReadinessReport } from '@/types/readiness';
import { FilterBar, ReadinessView, scoreText, selectClass } from './readiness-view';
import { EvidenceForm } from './evidence-form';
import { PolicyEditor } from './policy-editor';
export function CoordinatorReadiness() {
  const [query, setQuery] = useState<ReadinessQuery>({ months: '3' }); const [tab, setTab] = useState('Overview'); const [selected, setSelected] = useState('');
  const [search, setSearch] = useState(''); const [readiness, setReadiness] = useState(''); const [department, setDepartment] = useState(''); const [batch, setBatch] = useState(''); const [skill, setSkill] = useState(''); const [minimum, setMinimum] = useState(''); const [eligible, setEligible] = useState('');
  const load = useCallback(async () => { const [cohort, policies] = await Promise.all([getCohortReadiness(query), listReadinessPolicies()]); return { ...cohort, policies: policies.policies }; }, [query]);
  const { data, loading, error, refresh } = useCommunityData(load);
  if (!data && loading) return <PageSkeleton label="Loading student readiness" />;
  if (error || !data) return <LoadError message={error || 'Unable to load readiness'} onRetry={refresh} />;
  const rows = data.students.filter(row => `${row.student.name} ${row.student.registrationNumber}`.toLowerCase().includes(search.toLowerCase()) && (!readiness || row.status === readiness) && (!department || row.student.department === department) && (!batch || row.student.batch === batch) && (!eligible || row.eligibility.status === eligible) && (!skill || minimum === '' || row.skills.some(item => item.key === skill && item.score !== null && item.score >= Number(minimum))));
  return <><SectionIntro eyebrow="Placement intelligence" title="Student readiness & shortlisting" description="Use demonstrated skills, recent evidence, and role-specific requirements to make accountable placement decisions." action={<Button variant="outline" disabled={loading} onClick={refresh}>Refresh</Button>} />
    <FilterBar policies={data.policies} query={query} onChange={setQuery} />
    <div className="flex flex-wrap gap-2">{['Overview', 'Record evaluation', 'Scoring policies'].map(label => <Button key={label} variant={tab === label ? 'default' : 'outline'} onClick={() => { setTab(label); setSelected(''); }}>{label}</Button>)}</div>
    {loading && <p role="status" className="text-sm text-primary">Updating analytics…</p>}
    {tab === 'Scoring policies' ? <PolicyEditor key={data.policy._id} initial={data.policy} onSaved={policy => { setQuery(current => ({ ...current, policy: policy._id })); }} /> : tab === 'Record evaluation' ? <EvidenceForm key={data.policy._id} policy={data.policy} students={data.students.map(row => row.student)} onSaved={refresh} /> : selected ? <StudentDrilldown studentId={selected} query={query} onBack={() => { setSelected(''); refresh(); }} /> : <>
      <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{['Placement Ready', 'Almost Ready', 'Needs Improvement', 'Not Ready', 'Insufficient Evidence'].map(status => <Card key={status}><CardContent className="p-4"><p className="text-sm text-muted-foreground">{status}</p><p className="mt-2 text-3xl font-semibold">{data.students.filter(student => student.status === status).length}</p></CardContent></Card>)}</div>
      <Card><CardHeader><CardTitle>Shortlist candidates</CardTitle></CardHeader><CardContent className="space-y-4"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Input aria-label="Search students" placeholder="Name or registration number" value={search} onChange={event => setSearch(event.target.value)} />
        <select aria-label="Readiness status" className={selectClass} value={readiness} onChange={event => setReadiness(event.target.value)}><option value="">All readiness levels</option>{['Placement Ready', 'Almost Ready', 'Needs Improvement', 'Not Ready', 'Insufficient Evidence'].map(value => <option key={value}>{value}</option>)}</select>
        <select aria-label="Department" className={selectClass} value={department} onChange={event => setDepartment(event.target.value)}><option value="">All departments</option>{[...new Set(data.students.map(row => row.student.department).filter(Boolean))].map(value => <option key={value}>{value}</option>)}</select>
        <select aria-label="Batch" className={selectClass} value={batch} onChange={event => setBatch(event.target.value)}><option value="">All batches</option>{[...new Set(data.students.map(row => row.student.batch).filter(Boolean))].map(value => <option key={value}>{value}</option>)}</select>
        <select aria-label="Company eligibility" className={selectClass} value={eligible} onChange={event => setEligible(event.target.value)}><option value="">All eligibility outcomes</option>{['Eligible', 'Nearly Eligible', 'Not Eligible'].map(value => <option key={value}>{value}</option>)}</select>
        <select aria-label="Filter skill" className={selectClass} value={skill} onChange={event => setSkill(event.target.value)}><option value="">Any skill</option>{data.policy.skills.map(skill => <option key={skill.key} value={skill.key}>{skill.label}</option>)}</select><Input aria-label="Minimum skill score" placeholder="Minimum skill score / 10" type="number" min="0" max="10" step="0.1" disabled={!skill} value={minimum} onChange={event => setMinimum(event.target.value)} /></div>
        <p className="text-sm text-muted-foreground">{rows.length} of {data.students.length} students · company academic requirements are defined in the selected policy</p>
        {rows.map(row => <button key={row.student.id} className="w-full rounded-lg border p-4 text-left hover:border-primary focus-visible:ring-2" onClick={() => setSelected(row.student.id)}><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-semibold">{row.student.name}</p><p className="text-xs text-muted-foreground">{row.student.registrationNumber} · {row.student.department || 'Department not set'} · {row.student.batch} · {row.student.section?.name || 'Unassigned'}</p></div><div className="flex flex-wrap items-center gap-2"><span className="text-xl font-semibold">{scoreText(row.overall)}/10</span><Badge variant="outline">{row.status}</Badge><Badge variant="outline">{row.eligibility.status}</Badge></div></div><p className="mt-2 text-sm text-muted-foreground">{row.eligibility.reasons.slice(0, 2).join(' · ') || 'Meets the selected policy requirements'}</p>{row.decision && <p className="mt-2 text-sm">Coordinator: {row.decision.decision} — {row.decision.reason}</p>}</button>)}
        {!rows.length && <p className="py-8 text-center text-muted-foreground">No students match these filters.</p>}
      </CardContent></Card>
    </>}
  </>;
}
function StudentDrilldown({ studentId, query, onBack }: { studentId: string; query: ReadinessQuery; onBack: () => void }) {
  const load = useCallback(() => getReadiness(query, studentId), [query, studentId]);
  const { data, loading, error, refresh } = useCommunityData(load);
  if (!data && loading) return <PageSkeleton label="Loading student evidence" />;
  if (error || !data) return <LoadError message={error || 'Unable to load student'} onRetry={refresh} />;
  return <div className="space-y-4"><Button variant="outline" onClick={onBack}>Back to candidates</Button><h2 className="text-2xl font-semibold">{data.student.name}</h2><ReadinessView report={data} /><DecisionForms report={data} query={query} onSaved={refresh} />
    <Card><CardHeader><CardTitle>Decision history</CardTitle></CardHeader><CardContent className="space-y-3">{data.decisions.length ? data.decisions.map(decision => <div key={decision._id} className="rounded-md border p-3"><p className="font-semibold">{decision.decision}</p><p>{decision.reason}</p><p className="text-xs text-muted-foreground">{decision.recordedBy?.name || 'Coordinator'} · {new Date(decision.createdAt).toLocaleString()}</p></div>) : <p className="text-sm text-muted-foreground">No coordinator decision recorded for this policy version.</p>}</CardContent></Card>
  </div>;
}
function DecisionForms({ report, query, onSaved }: { report: ReadinessReport; query: ReadinessQuery; onSaved: () => void }) {
  const [decision, setDecision] = useState('Hold'); const [reason, setReason] = useState(''); const [cgpa, setCgpa] = useState(String(report.academics?.cgpa ?? '')); const [backlogs, setBacklogs] = useState(String(report.academics?.backlogs ?? '')); const [year, setYear] = useState(String(report.academics?.graduationYear ?? '')); const [academicReason, setAcademicReason] = useState(''); const [pending, setPending] = useState(false); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  async function save(action: () => Promise<unknown>) { setPending(true); setError(''); setMessage(''); try { await action(); setMessage('Record saved.'); onSaved(); } catch (error) { setError(error instanceof Error ? error.message : 'Unable to save record'); } finally { setPending(false); } }
  return <Card><CardHeader><CardTitle>Coordinator decision & academic verification</CardTitle></CardHeader><CardContent className="space-y-5"><form className="space-y-3" onSubmit={event => { event.preventDefault(); void save(() => recordShortlistDecision(report.student.id, { ...query, policy: report.policy._id }, decision, reason)); }}><fieldset disabled={pending} className="space-y-3"><label className="block text-sm font-medium">Coordinator decision<select aria-label="Coordinator decision" className={selectClass} value={decision} onChange={event => setDecision(event.target.value)}>{['Shortlisted', 'Hold', 'Needs Training', 'Not Eligible'].map(value => <option key={value}>{value}</option>)}</select></label><label className="block text-sm font-medium">Decision / override reason<Input required maxLength={2000} value={reason} onChange={event => setReason(event.target.value)} /></label><Button type="submit" disabled={pending}>Record decision</Button><p className="text-xs text-muted-foreground">System recommendation: {report.eligibility.status}. This decision records the policy, evidence IDs, score, window, and your reason for audit.</p></fieldset></form>
    <form className="space-y-3 border-t pt-4" onSubmit={event => { event.preventDefault(); void save(() => recordAcademics(report.student.id, { cgpa: Number(cgpa), backlogs: Number(backlogs), graduationYear: Number(year), reason: academicReason })); }}><fieldset disabled={pending} className="grid gap-3 sm:grid-cols-3"><label className="text-sm font-medium">Verified CGPA<Input type="number" required min="0" max="10" step="0.1" value={cgpa} onChange={event => setCgpa(event.target.value)} /></label><label className="text-sm font-medium">Active backlogs<Input type="number" required min="0" max="100" value={backlogs} onChange={event => setBacklogs(event.target.value)} /></label><label className="text-sm font-medium">Graduation year<Input type="number" required min="2000" max="2100" value={year} onChange={event => setYear(event.target.value)} /></label><label className="text-sm font-medium sm:col-span-3">Verification source / reason<Input required maxLength={2000} value={academicReason} onChange={event => setAcademicReason(event.target.value)} /></label><Button type="submit" disabled={pending}>Record academics</Button></fieldset></form>
    {error && <p role="alert" className="text-destructive">{error}</p>}{message && <p role="status" className="text-primary">{message}</p>}
  </CardContent></Card>;
}
