import { useState } from 'react';
import { createReadinessPolicy } from '@/services/readiness.api.service';
import type { ReadinessPolicy } from '@/types/readiness';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
export function PolicyEditor({ initial, onSaved }: { initial: ReadinessPolicy; onSaved: (policy: ReadinessPolicy) => void }) {
  const [draft, setDraft] = useState(initial); const [years, setYears] = useState(initial.graduationYears.join(', ')); const [pending, setPending] = useState(false); const [error, setError] = useState('');
  return <Card><CardHeader><CardTitle>Role / company scoring rules</CardTitle></CardHeader><CardContent><p className="mb-4 text-sm text-muted-foreground">Saving creates an immutable version. Change the policy key to create a separate company or role. Calibrate thresholds against real placement outcomes before using them for operational shortlisting.</p>
    <form onSubmit={async event => { event.preventDefault(); setPending(true); setError(''); try { const result = await createReadinessPolicy({ ...draft, graduationYears: years.trim() ? years.split(',').map(value => Number(value.trim())) : [] }); onSaved(result.policy); } catch (error) { setError(error instanceof Error ? error.message : 'Unable to save policy'); } finally { setPending(false); } }}>
      <fieldset disabled={pending} className="space-y-4"><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-medium">Role / company label<Input required maxLength={100} value={draft.label} onChange={event => setDraft({ ...draft, label: event.target.value })} /></label><label className="text-sm font-medium">Policy key<Input required pattern="[a-z0-9-]+" maxLength={80} value={draft.key} onChange={event => setDraft({ ...draft, key: event.target.value })} /></label></div>
      <div className="space-y-3">{draft.skills.map((skill, index) => <div key={index} className="grid gap-3 rounded-lg border p-3 sm:grid-cols-2 xl:grid-cols-6">{(['key', 'label', 'weight', 'minimum'] as const).map(field => <label key={field} className="text-xs font-medium capitalize">{field === 'minimum' ? 'Minimum / 10' : field}<Input required type={field === 'weight' || field === 'minimum' ? 'number' : 'text'} min={field === 'weight' ? 1 : 0} max={field === 'minimum' ? 10 : field === 'weight' ? 100 : undefined} step="0.1" value={skill[field]} onChange={event => setDraft({ ...draft, skills: draft.skills.map((item, i) => i === index ? { ...item, [field]: field === 'weight' || field === 'minimum' ? Number(event.target.value) : event.target.value } : item) })} /></label>)}<label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={skill.mandatory} onChange={event => setDraft({ ...draft, skills: draft.skills.map((item, i) => i === index ? { ...item, mandatory: event.target.checked } : item) })} />Mandatory</label><Button type="button" variant="outline" disabled={draft.skills.length === 1} onClick={() => setDraft({ ...draft, skills: draft.skills.filter((_, i) => i !== index) })}>Remove</Button></div>)}</div>
      <Button type="button" variant="outline" disabled={draft.skills.length >= 30} onClick={() => setDraft({ ...draft, skills: [...draft.skills, { key: '', label: '', weight: 10, minimum: 6, mandatory: true }] })}>Add skill</Button>
      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{([['minSamples', 'Minimum recent independent evaluations', 1, 20], ['freshnessDays', 'Evidence freshness (days)', 1, 365], ['halfLifeDays', 'Recency half-life (days)', 1, 365], ['readyScore', 'Placement-ready score / 10', 1, 10], ['almostScore', 'Almost-ready score / 10', 0, 10]] as const).map(([key, label, min, max]) => <label key={key} className="text-sm font-medium">{label}<Input required type="number" min={min} max={max} step={key.endsWith('Score') ? '0.1' : '1'} value={draft[key]} onChange={event => setDraft({ ...draft, [key]: Number(event.target.value) })} /></label>)}
      <label className="text-sm font-medium">Minimum CGPA (optional)<Input type="number" min="0" max="10" step="0.1" value={draft.minCgpa ?? ''} onChange={event => setDraft({ ...draft, minCgpa: event.target.value === '' ? null : Number(event.target.value) })} /></label><label className="text-sm font-medium">Maximum backlogs (optional)<Input type="number" min="0" max="100" value={draft.maxBacklogs ?? ''} onChange={event => setDraft({ ...draft, maxBacklogs: event.target.value === '' ? null : Number(event.target.value) })} /></label><label className="text-sm font-medium">Graduation years (optional)<Input placeholder="2026, 2027" value={years} onChange={event => setYears(event.target.value)} /></label></div>
      <Button type="submit" disabled={pending}>{pending ? 'Saving…' : 'Save new policy version'}</Button></fieldset>{error && <p role="alert" className="mt-3 text-destructive">{error}</p>}
    </form>
  </CardContent></Card>;
}
