import type { ReactNode } from 'react';
import type { ReadinessPolicy, ReadinessQuery, ReadinessReport } from '@/types/readiness';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
export const scoreText = (value: number | null | undefined) => value == null ? '—' : value.toFixed(1);
export const selectClass = 'h-11 w-full rounded-md border bg-white px-3 text-sm';
export function FilterBar({ policies, query, onChange, children }: { policies: ReadinessPolicy[]; query: ReadinessQuery; onChange: (query: ReadinessQuery) => void; children?: ReactNode }) {
  return <div className="grid gap-3 rounded-lg border bg-white p-4 sm:grid-cols-2 xl:grid-cols-4"><label className="text-sm font-medium">Target role / company<select aria-label="Target role or company" className={selectClass} value={query.policy || ''} onChange={event => onChange({ ...query, policy: event.target.value })}><option value="">Default role</option>{policies.map(policy => <option key={policy._id} value={policy._id}>{policy.label} · v{policy.version}</option>)}</select></label>
    <label className="text-sm font-medium">Evidence window<select aria-label="Evidence window" className={selectClass} value={query.months || 'custom'} onChange={event => onChange({ policy: query.policy, ...(event.target.value === 'custom' ? { from: new Date(Date.now() - 90 * 86400000).toISOString().slice(0, 10), to: new Date().toISOString().slice(0, 10) } : { months: event.target.value }) })}><option value="3">3 months</option><option value="4">4 months</option><option value="6">6 months</option><option value="custom">Custom dates</option></select></label>
    {!query.months && <><label className="text-sm font-medium">From (UTC)<input aria-label="From date" type="date" className={selectClass} value={query.from || ''} onChange={event => onChange({ ...query, from: event.target.value })} /></label><label className="text-sm font-medium">To (UTC)<input aria-label="To date" type="date" className={selectClass} value={query.to || ''} onChange={event => onChange({ ...query, to: event.target.value })} /></label></>}{children}</div>;
}
export function ReadinessView({ report }: { report: ReadinessReport }) {
  const { activity } = report;
  const points = report.history.map((point, index) => point.overall === null ? null : `${30 + index * 100},${180 - point.overall * 15}`).filter(Boolean).join(' ');
  return <>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[
      ['Readiness', `${scoreText(report.overall)} / 10`, report.status],
      ['Active learning', `${activity.activeMinutes} min`, `${activity.activeDays} active days · ${activity.streak} day streak`],
      ['Problems solved', `${activity.problemsSolved} / ${activity.problemsAttempted}`, `${activity.submissions} submissions · self-reported`],
      ['Assessments completed', String(activity.assessmentsCompleted), `${activity.gradedAttempts} graded attempts · ${activity.pendingReview} awaiting review`],
    ].map(([label, value, detail]) => <Card key={label}><CardContent className="p-5"><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 text-3xl font-semibold tabular-nums">{value}</p><p className="mt-2 text-sm text-muted-foreground">{detail}</p></CardContent></Card>)}</div>
    <Card><CardContent className="space-y-3 p-5"><div className="flex flex-wrap items-center gap-2"><Badge>{report.eligibility.status}</Badge><Badge variant="outline">{report.coverage}% skill-weight coverage</Badge><Badge variant="outline">{report.evidenceCount} scored records</Badge><Badge variant="outline">{report.policy.label} · v{report.policy.version}</Badge></div>
      {report.provisional && <p className="font-medium text-amber-700">Provisional score: some skills lack sufficient evidence. Missing evidence is not a zero.</p>}
      <p className="text-sm text-muted-foreground">{report.formula}</p>
      <p className="text-xs text-muted-foreground">Active time is browser-reported on learning pages, paused when hidden, unfocused, or idle for 60 seconds. It is not a measure of ability. Readiness rules are configurable decision support, not a hiring probability.</p>
      {report.eligibility.reasons.length > 0 && <ul className="list-disc space-y-1 pl-5 text-sm">{report.eligibility.reasons.map(reason => <li key={reason}>{reason}</li>)}</ul>}
    </CardContent></Card>
    <div className="grid gap-4 xl:grid-cols-2"><Card><CardHeader><CardTitle>Readiness over the selected window</CardTitle></CardHeader><CardContent>{points ? <svg role="img" aria-label="Readiness trend from zero to ten" viewBox="0 0 560 220" className="w-full"><path d="M30 30 V180 H535" fill="none" stroke="#cbd5e1" /><text x="4" y="36" fontSize="12">10</text><text x="12" y="180" fontSize="12">0</text><polyline points={points} fill="none" stroke="#2563eb" strokeWidth="3" />{report.history.map((point, index) => point.overall !== null && <g key={point.at}><circle cx={30 + index * 100} cy={180 - point.overall * 15} r="4" fill="#2563eb" /><text x={30 + index * 100} y="204" textAnchor="middle" fontSize="11">{point.at.slice(5, 10)}</text></g>)}</svg> : <p className="py-12 text-center text-muted-foreground">Complete graded assessments to build your trend.</p>}<p className="text-xs text-muted-foreground">Recomputed with this policy version at each checkpoint. Early points may have insufficient evidence.</p></CardContent></Card>
    <Card><CardHeader><CardTitle>Learning consistency</CardTitle></CardHeader><CardContent><div className="flex h-40 items-end gap-1 overflow-x-auto" aria-label="Active minutes by day">{report.daily.length ? report.daily.map(day => <div key={day.day} title={`${day.day}: ${day.minutes} minutes`} className="min-w-3 flex-1 rounded-t bg-blue-500" style={{ height: `${Math.max(2, day.minutes / Math.max(...report.daily.map(item => item.minutes), 1) * 100)}%` }} />) : <p className="m-auto text-sm text-muted-foreground">No active learning recorded in this window.</p>}</div><p className="mt-3 text-xs text-muted-foreground">UTC days with recorded activity. A streak day needs at least one tracked minute. Time never adds readiness points.</p></CardContent></Card></div>
    <div className="grid gap-4 lg:grid-cols-2">{report.skills.map(skill => <Card key={skill.key}><CardHeader><div className="flex items-center justify-between"><CardTitle>{skill.label}</CardTitle><span className="text-xl font-semibold">{scoreText(skill.score)} / 10</span></div></CardHeader><CardContent className="space-y-3"><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full bg-blue-600" style={{ width: `${(skill.score || 0) * 10}%` }} /></div><p className="text-sm text-muted-foreground">{skill.mandatory ? 'Required' : 'Optional'} · minimum {skill.minimum}/10 · weight {skill.weight} · {skill.recentSamples}/{report.policy.minSamples} recent independent evaluations</p><div className="flex flex-wrap gap-2"><Badge variant="outline">{skill.trend}</Badge><Badge variant="outline">{skill.consistency}</Badge></div><p className="text-sm">{skill.recommendation}</p><p className="text-xs text-muted-foreground">First-attempt average: {scoreText(skill.firstAverage)} · latest: {scoreText(skill.latestAverage)} · last evaluated: {skill.lastAt?.slice(0, 10) || 'Never'}</p><div className="grid grid-cols-3 gap-2">{skill.difficulties.map(item => <div key={item.difficulty} className="rounded-md border p-2 text-xs"><p className="capitalize">{item.difficulty}</p><p className="font-semibold">{scoreText(item.score)} / 10</p><p>{item.samples} evaluations</p></div>)}</div></CardContent></Card>)}</div>
    <Card><CardHeader><CardTitle>Evidence history</CardTitle></CardHeader><CardContent className="space-y-3">{report.evidence.length ? report.evidence.map(item => <div key={item.id} className="flex flex-wrap items-center justify-between gap-3 rounded-md border p-3"><div><p className="font-semibold">{item.title}</p><p className="text-xs text-muted-foreground">{item.skill} · {item.difficulty} · {item.source} · {item.at.slice(0, 10)}</p></div><span className="font-semibold">{item.percentage === null ? 'Practice log' : `${item.score}/${item.maxScore} (${item.percentage}%)`}</span></div>) : <p className="text-sm text-muted-foreground">No evidence recorded for this window.</p>}</CardContent></Card>
  </>;
}
