import { parseStudentCsv } from '@/lib/student-csv';
import { useState } from 'react';
import { bulkImportStudents } from '@/services/users.api.service';
import { InfoTip } from '@/components/common/info-tip';
import { Button } from '@/components/ui/button';
import type { SectionRow } from '@/types/admin';
export function BulkStudents({ sections, onImported }: { sections: SectionRow[]; onImported: () => Promise<void> }) {
  const [rows, setRows] = useState<Record<string, string>[]>([]); const [section, setSection] = useState(''); const [pending, setPending] = useState(false); const [error, setError] = useState('');
  const [results, setResults] = useState<{ row: number; email: string; status: string; temporaryPassword?: string; error?: string }[]>([]);
  return <details className="rounded-xl border bg-white p-4"><summary className="cursor-pointer font-semibold">Bulk upload students <InfoTip text="Upload a CSV with headers name,email,registrationNumber,phoneNumber,department,batch. Name and email are required. Select a cohort, preview up to 100 rows, then import. Duplicate emails are reported without creating another account. Temporary passwords appear after import." /></summary><div className="mt-4 space-y-3"><a className="text-sm text-primary underline" download="students-template.csv" href="data:text/csv;charset=utf-8,name%2Cemail%2CregistrationNumber%2CphoneNumber%2Cdepartment%2Cbatch%0A">Download CSV template</a><input aria-label="Student CSV file" type="file" accept=".csv,text/csv" disabled={pending} className="block w-full" onChange={async e => { const file = e.target.files?.[0]; setRows([]); setResults([]); setError(''); if (!file) return; try { if (file.size > 1024 * 1024) throw new Error('CSV must be smaller than 1 MB.'); setRows(parseStudentCsv(await file.text())); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to read CSV'); } }} /><select aria-label="Import cohort" className="h-11 w-full rounded-md border px-3" value={section} onChange={e => setSection(e.target.value)} disabled={pending}><option value="">Select cohort</option>{sections.filter(s => s.status === 'Active').map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select>{rows.length > 0 && <div className="max-h-64 overflow-auto rounded-lg border"><table className="w-full text-left text-sm"><thead><tr><th className="p-2">Name</th><th>Email</th></tr></thead><tbody>{rows.map((r, i) => <tr key={i}><td className="p-2">{r.name}</td><td>{r.email}</td></tr>)}</tbody></table></div>}<Button disabled={pending || !rows.length || !section} onClick={async () => { setPending(true); setError(''); try { const result = await bulkImportStudents(rows.map(r => ({ ...r, section }))); setResults(result.results); setRows(rows.filter((_, i) => result.results[i]?.status === 'failed')); await onImported(); } catch (e) { setError(e instanceof Error ? e.message : 'Import failed'); } finally { setPending(false); } }}>{pending ? 'Importing…' : `Import ${rows.length} students`}</Button>{error && <p role="alert" className="text-destructive">{error}</p>}{results.length > 0 && <div className="space-y-2"><p className="font-medium">{results.filter(r => r.status === 'created').length} created · {results.filter(r => r.status === 'failed').length} failed</p>{results.map(r => <p key={r.row} className="break-words text-sm">{r.email}: {r.status === 'created' ? `Created · temporary password: ${r.temporaryPassword}` : r.error}</p>)}</div>}</div></details>;
}
