import { useState } from 'react';
import { listPracticePeers } from '@/services/groups.api.service';
import { createGroup, listGroups } from '@/services/groups.api.service';
import { useCommunityData } from '@/sections/community/use-community-data';
import { GroupRoom } from '@/sections/community/group-room';
import { SectionIntro } from '@/components/common/section-intro';
import { PageSkeleton, LoadError } from '@/components/common/loading-state';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
const load = async () => { const [groups, peers] = await Promise.all([listGroups(), listPracticePeers()]); return { ...groups, ...peers }; };
export function SelfAssessmentSection({ onLaunch }: { onLaunch: (title: string) => void }) {
  const { data, loading, error, refresh } = useCommunityData(load);
  const [opened, setOpened] = useState(''); const [creating, setCreating] = useState(false);
  const [name, setName] = useState(''); const [mode, setMode] = useState('Group Discussion'); const [description, setDescription] = useState(''); const [students, setStudents] = useState<string[]>([]); const [pending, setPending] = useState(false); const [actionError, setActionError] = useState('');
  if (!data && loading) return <PageSkeleton />;
  if (error) return <LoadError message={error} onRetry={refresh} />;
  const group = data?.groups.find(g => g._id === opened);
  if (group) return <GroupRoom key={group._id} group={group} onBack={() => setOpened('')} />;
  return <><SectionIntro eyebrow="Student practice" title="Self-Assessment" description="Create your own practice room. Invite peers for discussions, mock interviews, written practice, or DSA hackathons." action={<Button onClick={() => setCreating(v => !v)}>{creating ? 'Close' : 'Create practice room'}</Button>} />{creating && <form className="space-y-4 rounded-xl border bg-white p-5" onSubmit={async e => { e.preventDefault(); setPending(true); setActionError(''); try { await createGroup({ name, description, students, mode }); setCreating(false); setName(''); setDescription(''); setStudents([]); refresh(); onLaunch('Practice room created'); } catch (e) { setActionError(e instanceof Error ? e.message : 'Unable to create practice room'); } finally { setPending(false); } }}><fieldset disabled={pending} className="space-y-3"><label className="block text-sm">Title<Input required maxLength={120} value={name} onChange={e => setName(e.target.value)} /></label><label className="block text-sm">Format<select className="h-11 w-full rounded-md border px-3" value={mode} onChange={e => setMode(e.target.value)}>{['Written Test', 'Mock Interview', 'Group Discussion', 'DSA Hackathon'].map(m => <option key={m}>{m}</option>)}</select></label><label className="block text-sm">Questions, topics, or challenge rules<textarea required maxLength={2000} className="min-h-32 w-full rounded-md border p-3" value={description} onChange={e => setDescription(e.target.value)} /></label><details><summary className="cursor-pointer">Invite classmates (optional · {students.length} selected)</summary><div className="max-h-64 overflow-auto">{data?.peers.map(p => <label key={p._id} className="flex gap-2 p-2"><input type="checkbox" checked={students.includes(p._id)} onChange={e => setStudents(ids => e.target.checked ? [...ids, p._id] : ids.filter(id => id !== p._id))} />{p.name} · {p.registrationNumber}</label>)}</div></details><Button disabled={pending}>{pending ? 'Creating…' : 'Create and invite'}</Button></fieldset>{actionError && <p role="alert" className="text-destructive">{actionError}</p>}</form>}<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{data?.groups.filter(g => g.kind === 'practice').map(g => <button key={g._id} className="rounded-xl border bg-white p-5 text-left hover:border-primary" onClick={() => setOpened(g._id)}><h2 className="font-semibold">{g.name}</h2><p className="mt-2 text-sm text-muted-foreground">{g.mode} · {g.participants.length} participants</p></button>)}</div>{!data?.groups.some(g => g.kind === 'practice') && <p className="text-muted-foreground">No practice rooms yet. Create one for yourself or invite classmates.</p>}</>;
}
